### ISSUE TITLE
ruacbd.com

### ISSUE THREAD

**Issue by subti37** [THUMLP/SaMoE#2]
https://github.com/THUMLP/SaMoE/blame/8d005c4ea26a9741601416f847b66dbf619efe9e/data/all_csv/1-2112260-1.html.csv#L24  ruacbdresult

**Comment by subti37** [comment]
ruacbd

**Comment by subti37** [comment]
2023

**Comment by Zhouyx17** [comment]
> 2023

Hi, this dataset is created by Wenhu Chen [https://github.com/wenhuchen/Table-Fact-Checking](url), please contact them for errors in the dataset, thanks!
